run:
  timeout: 5m

linters:
  # We run with all default linters enabled and in addition the linters
  # listed below.
  enable:
    - bodyclose
    - errorlint
    - exportloopref
    - goimports
    - gosec
    - makezero
    - revive
    - unconvert
    - wastedassign

linters-settings:
  goimports:
    local-prefixes: github.com/kanonji/tables-to-go

  gosec:
    config:
      G306: "0666"
